# Generated by Django 2.2 on 2020-09-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
