# Generated by Django 2.2 on 2020-10-02 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_auto_20201001_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='password',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='username',
        ),
    ]
